### ISSUE TITLE
Move API key to environment variable

### ISSUE THREAD

**Issue by goodecf** [bottleware/weather#19]
Currently the API key is stored publicly where anyone can view it. It should be stored [securely](https://hackernoon.com/how-to-use-environment-variables-keep-your-secret-keys-safe-secure-8b1a7877d69c) in an environment variable.

**Comment by dozoyo** [comment]
If it was a secret, then yes you'd want to do that. I was mistaken when I originally brought this up.

It's a public key, therefore you don't have to hide it. It's going to be visible to anyone using the app. They can look at the network requests to grab it themselves.

**Comment by goodecf** [comment]
Is it a public key? I had to sign up for it.

**Comment by dozoyo** [comment]
Yes, it's a public key because the end user will see it, to make the request. The reason you had to sign up for it is to prevent anonymous people from abusing the API.

**Comment by goodecf** [comment]
Makes sense. Closing this.
