### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by dozoyo** [bottleware/weather#4]
Currently the `README.md` is the default `create-react-app` readme. 

It would be more clarifying to have a custom `README.md`. We can use the space to detail what this project is about, how to build it, as well as give links to where it resides, such as Netlify. What to expect of this project and all. 

Basically whatever you wish to communicate to others about this project.

I would suggest going to open source projects you like to copy what they do in their `README.md`

**Comment by dozoyo** [comment]
@goodecf 
https://old.reddit.com/r/cscareerquestions/comments/h17blk/always_write_a_clear_readme_if_you_want_to_find_a/

**Comment by goodecf** [comment]
Done!
